version: '2'

services:
    kong:
        image: kong
        restart: always
        ports:
            - 8000:8000
            - 8443:8443
            - 8001:8001
        expose:
            - 7946
            - 7946/udp
        environment:
            - KONG_DATABASE=postgres
            - KONG_PG_HOST=kong-database
        links:
            - kong-database:kong-database
        depends_on:
            - kong-database

    kong-database:
        image: postgres:9.4
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=kong
            - PSOTGRES_DB=kong
